Начинаем программировать
htmlacademy-react/1941977-what-to-watch-9 pull request #3
Opened 2022-02-18 15:02 UTC by Gantelia

---
:mortar_board: [Начинаем программировать](https://up.htmlacademy.ru/react/9/user/1941977/tasks/3)

2022-02-18 15:11 UTC, Gantelia commented on project/src/components/main-screen/main-screen.tsx
> +                </li>)).join('')
Не понимаю, как добавлять какую-либо логику в компоненты.  Новый синтаксис - сплошные ошибки. Здесь не выдает ошибок, но в отрисовке получаю 'object Object'. Пыталась выписать map отдельной функцией для вызова внутри компонента и передать пропс с массивом жанров ей аргументом - вообще не смогла сделать без ошибок. Нужен ли join здесь, раз это не html?

2022-02-18 15:19 UTC, Gantelia commented
Я не стала выписывать пропсы остальным компонентам по примеру учебного проекта. Начала, но поняла, что нужно слишком много раз повторять типизацию одних и тех же пропсов. Еще не поняла, как быть с массивом жанров. Сейчас я выписала вручную один объект для него. Потом можно будет автоматически создать массив или нужно уже сейчас захардкодить жанры?

2022-02-19 07:06 UTC, ant1quar requested changes

2022-02-19 07:39 UTC, ant1quar commented on project/src/components/main-screen/main-screen.tsx
> +                </li>)).join('')
убери join('')

2022-02-19 20:18 UTC, merged